org: weilai
service: bannerService

provider:
  name: aws
  runtime: nodejs22.x
  region: "us-west-1"
  environment:
    BUCKET_NAME: !Ref BannerImagesBucket
    DYNAMO_TABLE: !Ref BannersTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: !Join ["", ["arn:aws:s3:::", !Ref BannerImagesBucket, "/*"]]
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: !GetAtt BannersTable.Arn

resources:
  Resources:
    BannerImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-weilai-dev-123-new

# 可修改Bucket policy:        
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Effect": "Allow",
#             "Principal": "*",
#             "Action": "s3:GetObject",
#             "Resource": "arn:aws:s3:::banner-images-weilai-dev-123-new/*"
#         }
#     ]
# }

    BannersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Banners
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH

functions:
  getUploadUrl:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
  getAllBanners:
    handler: handlers/getAllBanners.getAllBanners
    events:
      - httpApi:
          path: /banners
          method: get
  confirmUpload:
    handler: handlers/confirmUpload.confirmUpload
    events:
      - s3:
          bucket: !Ref BannerImagesBucket
          event: s3:ObjectCreated:Put
          existing: true
