org: weilai

service: greet



provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
