org: weilai

service: greet



provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1

functions:
  greet:
    handler: handler.greet
    events:
      - httpApi:
          path: /greet
          method: get
  anotherGreet:
    handler: anotherGreet.anotherGreet
    events:
      - httpApi:
          path: /greet
          method: post        
